[book]
title = "Revision Control"
editor = "Tony Garnock-Jones"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/tonyg/revctrl.org/"
site-url = "https://tonyg.github.io/revctrl.org/"
